// NEW CATS: stepout:'Stepping out of the line', fbpos:'Full-back positioning', carry:'Carrying the ball', setp:'Defending set pieces'
QS2.def=[
{g:'your goal',cat:'line',role:'CENTER BACK',min:"20'",sc:'0-0',q:"Their midfielder has the ball in the centre circle. Their striker is level with you.",
 p:[['gk','us',34,2,'GK'],['me',0,30,26,''],['us',0,42,26,'CB'],['us',0,14,27,'FB'],['us',0,54,27,'FB'],['them',0,34,28.5,'ST'],['them',0,34,51,'CM'],['us',0,34,47,'CM'],['them',0,22,44,'CM'],['us',0,24,39,'CM']],ball:[35,50],
 o:[['Drop ten metres to protect the space behind',1,[30,26,30,16],"Feels safe, but he can't hit a long pass with a player right on him. Drop now and you leave a big gap between your defence and midfield for them to play into."],
    ['Hold the line where it is',2,[30,26,30,27],"Look at the ball: your midfielder is right on him, so he can't lift his head and hit it over you. Hold your line and keep the team compact. The moment he's free to look up, then you drop."],
    ['Step up ten metres to squeeze the space',0,[30,26,30,36],"The ball hasn't gone backwards and your line isn't stepping with you. Go on your own and one flick over the top puts their striker in behind."]],pro:1},
{g:'your goal',cat:'line',role:'CENTER BACK',min:"35'",sc:'0-0',q:"Their winger has the ball out wide and passes it.",
 p:[['gk','us',34,2,'GK'],['me',0,38,22,''],['us',0,26,22,'CB'],['us',0,14,23,'FB'],['us',0,54,27,'FB'],['them',0,59,33,'W'],['them',0,34,27,'ST'],['them',0,20,27,'W'],['them',0,47,45,'CM'],['us',0,40,38,'CM']],pass:[59,33,47.5,43.5],
 o:[['Step up together with your back line',2,[38,22,38,30],"Look at the pass: it's going backwards, away from your goal. That's your trigger. Step up together, quickly: their striker is left offside and there's less space for them to play into."],
    ['Hold your position',1,[38,22,38,23],"Not a disaster, but you give away free metres. Their midfielder can now play forward with your line still deep."],
    ['Drop to stay goal-side of the striker',0,[38,22,38,14],"Dropping when the ball goes backwards gives them space in front of your box and keeps everyone onside."]],pro:0},
{g:'your goal',cat:'delay',role:'LEFT BACK',min:"55'",sc:'1-0',q:"Their winger runs at you down the line. Their full-back is overlapping outside him.",
 p:[['gk','us',34,2,'GK'],['me',0,55,24,''],['them',0,53,35,'W'],['them',0,64,38,'FB'],['us',0,41,18,'CB'],['them',0,37,20,'ST'],['us',0,28,18,'CB'],['us',0,58,49,'W']],ball:[53.5,33.6],run:[58,49,63,41],
 o:[['Close the winger down fast and tackle',0,[55,24,53.5,33],"He just lays it outside to their full-back as you arrive, and you're out of the game."],
    ['Leave the winger and go with the overlap',1,[55,24,63,30],"Stops the pass outside, but now their winger has a free run inside at your center backs."],
    ['Back off slowly and stay between the two',2,[55,24,57,20],"Look behind them: your winger is sprinting back to take the overlapping full-back. Don't commit. Jockey backwards, stay in between so neither option is easy, and buy him the two seconds he needs."]],pro:2},
{g:'your goal',cat:'stepout',role:'CENTER BACK',min:"40'",sc:'0-0',q:"Their center back plays it into their 10, who has dropped into the space in front of you.",
 p:[['gk','us',34,2,'GK'],['me',0,36,26,''],['us',0,25,22,'CB'],['them',0,27,24.5,'ST'],['us',0,12,22,'FB'],['us',0,52,24,'FB'],['them',0,36,37,'10'],['us',0,26,48,'CM'],['us',0,44,48,'CM']],pass:[30,64,35.5,38.5],
 o:[['Step out and get tight on him before it arrives',2,[36,26,36,35],"Look behind you: your partner is already on their striker and your full-backs are tucked in. Nobody needs you in the line. Get tight before the ball arrives so he can't turn and run at your back four."],
    ['Stay in your back line',1,[36,26,36,25],"Your line stays neat, but he gets to turn with time, facing your defence, with your midfielders behind him."],
    ['Step out halfway and wait',0,[36,26,36,31],"The worst of both: you've left the line, but you're too far away to stop him turning."]],pro:0},
{g:'your goal',cat:'fbpos',role:'RIGHT BACK',min:"30'",sc:'0-0',q:"Their right winger has the ball on the far side.",
 p:[['gk','us',34,2,'GK'],['me',0,10,22,''],['us',0,28,20,'CB'],['us',0,40,20,'CB'],['us',0,54,26,'FB'],['them',0,59,34,'W'],['them',0,35,23,'ST'],['them',0,20,29,'CM'],['them',0,5,30,'W']],ball:[58,33],
 o:[['Stay wide, tight to their winger',1,[10,22,6,28],"He's about 50 metres from the ball. A pass that long hangs in the air, so you'd have time to get out to him. Staying wide just keeps the gap open."],
    ['Tuck in closer to your center back',2,[10,22,19,20],"Look at the gap between you and your center back: their midfielder is standing in it. Ball on the far side means you squeeze in. If they switch it, you get back out while the ball is in the air."],
    ['Drop deeper to cover behind your center backs',0,[10,22,18,12],"Dropping on your own plays their winger and midfielder onside behind your line."]],pro:1},
{cat:'fbpos',role:'LEFT BACK',min:"65'",sc:'0-0',q:"Your left winger has the ball, facing their full-back.",
 p:[['me',0,10,54,''],['us',0,8,40,'W'],['them',0,12,34,'FB'],['them',0,15,61,'W'],['us',0,26,67,'CB'],['us',0,42,67,'CB'],['them',0,34,59,'ST'],['us',0,30,46,'CM'],['them',0,32,42,'CM']],ball:[9,38.8],
 o:[['Overlap round the outside',1,[10,54,5,33],"It gives your winger a 2v1, and with more cover behind it's the right run. Here, if he loses it, their winger is free in the space you left."],
    ['Underlap on the inside',0,[10,54,19,37],"Same gap behind you, and you run straight into their midfield."],
    ['Stay behind him as his safe pass',2,[10,54,12,50],"Look behind you: their winger hasn't tracked back. He's waiting in your half. Go forward and lose it, and it's their winger and striker against your two center backs. Stay, and be the pass he can always play."]],pro:2},
{cat:'build',role:'RIGHT BACK',min:"15'",sc:'0-0',q:"Your center back passes to you near the touchline. Their winger comes to press you.",
 p:[['me',0,62,68,''],['us',0,44,77,'CB'],['them',0,37,69,'ST'],['them',0,55,63,'W'],['us',0,64,49,'W'],['them',0,51,44,'FB'],['us',0,44,56,'CM'],['them',0,44,52.5,'CM']],pass:[44,77,61,69],
 o:[['Play it back to your center back',1,[62,68,45.5,76.5],"Safe, but their striker is already moving across to press him. You've just moved the problem."],
    ['Pass it down the line to your winger',2,[62,68,64,50.5],"Look at their full-back: he's tucked in, 12 metres from your winger. Their winger coming to press you leaves the line open. One pass and you're past two of their players."],
    ['Pass inside to your midfielder',0,[62,68,45.5,57],"Their midfielder is right behind him. A pass through the middle of your own half is the one that gets intercepted."]],pro:1},
{g:'your goal',cat:'aerial',role:'LEFT BACK',min:"70'",sc:'1-1',q:"Their left winger is about to cross. You're at the back post.",
 p:[['gk','us',34,2,'GK'],['me',0,44,8,''],['them',0,51,12,'W'],['us',0,31,10,'CB'],['them',0,34,12.5,'ST'],['us',0,38,11,'CB'],['them',0,7,23,'W'],['us',0,12,18,'FB'],['them',0,27,21,'CM']],ball:[8.5,22],
 o:[['Hold the back post with your body open to him and the ball',2,[44,8,47,9.5],"Look over your shoulder: their right winger is coming in behind you. Stand where you can see the ball and him at the same time, so a high ball to the far post is yours, not his."],
    ['Move in to help your center backs',0,[44,8,39,10],"The middle is covered by your two center backs. Move in and their winger has the whole back post to himself."],
    ['Drop onto the goal line by the post',1,[44,8,38.5,1.5],"It might save a header on the line, but he gets a free jump at the ball in front of you."]],pro:0},
{g:'your goal',cat:'shape',role:'CENTER BACK',min:"30'",sc:'0-0',q:"A long clearance from their defence drops towards you.",
 p:[['me',0,33,42,''],['us',0,20,40,'CB'],['us',0,56,40,'FB'],['us',0,28,52,'CM'],['them',0,44,54,'ST'],['them',0,60,50,'W'],['them',0,20,58,'CM'],['us',0,46,62,'CM']],pass:[40,76,33.5,43],
 o:[['Head it straight back into their half',1,[33,42,40,68],"Never wrong, but you're giving them another 50/50 when the ball could be yours."],
    ['Head it back towards your keeper',0,[33,42,34,20],"A 40-metre header backwards is hard to judge. Get the weight wrong and you've handed them a chance for nothing."],
    ['Bring it down and pass to your midfielder',2,[33,42,28.5,50.5],"Look how far away their nearest player is: more than 10 metres. You have time. Cushion it on your chest or thigh and find your free midfielder."]],pro:2},
{cat:'carry',role:'CENTER BACK',min:"20'",sc:'0-0',q:"Your partner center back passes across to you.",
 p:[['me',0,24,70,''],['us',0,42,70,'CB'],['them',0,38,62,'ST'],['us',0,26,56,'CM'],['them',0,26,52,'CM'],['us',0,42,55,'CM'],['them',0,42,51,'CM'],['us',0,6,60,'FB'],['them',0,10,55,'W']],pass:[42,70,25.5,70],
 o:[['Carry the ball forward into the space',2,[24,70,22,59],"Look in front of you: nobody comes to press. Run it forward until someone has to leave his man to stop you. Then that man is free, and you pass to him."],
    ['Pass it straight back to your partner',1,[24,70,40.5,70],"Keeps the ball, but nothing changes and their striker can shift across again."],
    ['Play into your midfielder\'s feet now',0,[24,70,25.5,57.5],"Their midfielder is right behind him, waiting to step in. Draw a player out first."]],pro:0},
{cat:'build',role:'CENTER BACK',min:"70'",sc:'0-1',q:"Their front three press your back line. You have the ball.",
 p:[['gk','them',34,6,'GK'],['gk','us',34,98,'GK'],['me',0,40,78,''],['them',0,37,72,'ST'],['us',0,34,62,'CM'],['them',0,34,58.5,'CM'],['them',0,28,46,'CB'],['them',0,42,46,'CB'],['us',0,36,50,'ST']],ball:[40.5,76.6],run:[36,50,46,34],
 o:[['Pass into your midfielder',0,[40,78,34.5,63.5],"Their midfielder is tight on his back. Under this press, that's a turnover 35 metres from your goal."],
    ['Clip it in behind their back line for your striker',2,[40,78,47,32],"Look how high their back line is: there are 40 metres behind it, and your striker is already running. When they press with everyone, the space is behind them."],
    ['Pass back to your keeper',1,[40,78,34.5,96],"Safe for now, but their striker follows it and you face the same press even closer to your goal."]],pro:1},
{g:'your goal',cat:'setp',role:'CENTER BACK',min:"80'",sc:'2-1',q:"Corner against you. Your team defends it zonally, and your zone is in front of the near post.",
 p:[['gk','us',33,2,'GK'],['me',0,38,6,''],['us',0,32,6,'CB'],['us',0,26,7,'FB'],['us',0,34,11.5,'CM'],['them',0,33,18,'CB'],['them',0,41,14,'ST'],['them',0,26,14,'CM'],['them',0,67.5,0.5,'W']],ball:[66.5,1],
 o:[['Follow their big center back wherever he runs',0,[38,6,34,16],"Leave your zone and there's a hole at the near post, the exact space your team trusted you with."],
    ['Stand on the near post',1,[38,6,37.4,1.2],"Your keeper can handle the near post. On the line you can't attack anything."],
    ['Hold your zone and attack any ball into it',2,[38,6,39,7.5],"Look at your setup: your teammates are spread across the six-yard box, each owning a space. Their big man's run is meant to drag you out. Stay, and be first to any ball that comes into your zone."]],pro:2}
];
