// NEW CATS: press:'Pressing from the front', counter:'Counter-attacks', setp:'Set pieces'
QS2.ten=[
{cat:'move',role:'NUMBER 10',min:"25'",sc:'0-0',q:"Your midfielder has the ball. You're between their lines, waiting for it.",
 p:[['gk','them',34,3,'GK'],['me',0,31,31,''],['them',0,28.5,37,'DM'],['them',0,46,38,'CM'],['them',0,28,20,'CB'],['them',0,40,20,'CB'],['them',0,52,22,'FB'],['us',0,35,21,'ST'],['us',0,24,48,'CM'],['us',0,44,50,'CM']],ball:[25,47],
 o:[['Stay where you are and call for it',0,[31,31,31,32.5],"Look at their DM: he's standing right on the line between the ball and you. Ask for it there and he steps in and steals it."],
    ['Drift off his shoulder, into his blind side',2,[31,31,39,30],"Their DM is watching the ball, and he's screening you. Slide a few metres to the side he can't see and the lane opens up. You get it on the half-turn with nobody on you."],
    ['Drop deep next to your midfielder',1,[31,31,30,43],"You'd get the ball, but now you're in front of their midfield, not behind it. Good when there's no space between the lines. Here there is."]],pro:1},
{cat:'move',role:'NUMBER 10',min:"38'",sc:'0-1',q:"Your left-back is passing into your left winger, who has his back to goal.",
 p:[['gk','them',34,3,'GK'],['me',0,26,34,''],['us',0,7,26,'W'],['them',0,8,23,'FB'],['them',0,24,20,'CB'],['them',0,36,19,'CB'],['us',0,32,21,'ST'],['them',0,32,38,'CM'],['us',0,6,42,'FB']],pass:[6,42,7,27.5],
 o:[['Come inside to offer him a short pass',1,[26,34,19,30],"A fine option if he's in trouble. But you're only giving him a sideways ball while the big chance is behind their full-back."],
    ['Stay central and wait for a later ball',0,[26,34,31,30],"You're standing still while their whole left side is busy with your winger. That's the moment to go, not wait."],
    ['Run into the channel behind their full-back',2,[26,34,15,13],"Look at their full-back: he's glued to your winger's back, and their center back hasn't moved across. Run now and your winger can flick it first time round the corner into your path. Third-man run."]],pro:2},
{cat:'switchp',role:'NUMBER 10',min:"52'",sc:'1-1',q:"You get the ball in the left half-space. Two players are closing you down.",
 p:[['gk','them',34,3,'GK'],['me',0,20,30,''],['them',0,25,34,'CM'],['them',0,11,25,'FB'],['us',0,6,22,'W'],['them',0,28,19,'CB'],['them',0,40,19,'CB'],['them',0,49,21,'FB'],['us',0,63,23,'W'],['them',0,33,37,'CM']],ball:[21,29],
 o:[['Switch it yourself to your right winger',2,[20,30,61,23.5],"Look at their far full-back: he's tucked right in to help the middle, and your right winger is alone on the touchline. From my notes on Foden: when you're closed down, switch it yourself. It gives you much more space than if it goes back to the center back first."],
    ['Play it back to your center back to switch',1,[20,30,26,46],"Safe, and it still gets there. But it takes two extra passes, and by then their full-back has slid back out."],
    ['Play a one-two with your left winger',0,[20,30,7,23.5],"Their full-back is tight on him and there's a midfielder closing behind you. That corner is crowded. The free space is on the other side."]],pro:0},
{cat:'shoot',role:'NUMBER 10',min:"68'",sc:'0-0',q:"You've cut inside from the left onto your right foot. You're at the edge of the box.",
 p:[['gk','them',35.5,2.5,'GK'],['me',0,25,18,''],['them',0,23,23,'CM'],['them',0,30,13,'CB'],['them',0,38,12,'CB'],['us',0,34,13.5,'ST'],['them',0,48,12,'FB'],['us',0,46,22,'CM']],ball:[26,17],
 o:[['Slip it into your striker',0,[25,18,33,12],"Both center backs are right on him. The pass gets cut out, or he has to take it with his back to goal."],
    ['Curl it towards the far post',1,[25,18,37,-0.5],"It's the shot everyone expects from there. Your curl has to go round their center back, and the keeper is already leaning that way."],
    ['Drive it low to the near post',2,[25,18,31,-0.5],"Look at the keeper: he's cheated towards his far post, waiting for the curler. The near post is open. Hit it low and hard before he can shift back."]],pro:2},
{cat:'press',role:'NUMBER 10',min:"12'",sc:'0-0',q:"Their center back has the ball. Your striker is pressing him.",
 p:[['gk','them',34,3,'GK'],['them',0,24,14,'CB'],['them',0,44,13,'CB'],['us',0,30,16,'ST'],['them',0,33,25,'DM'],['me',0,38,32,''],['them',0,8,24,'FB'],['them',0,60,24,'FB'],['them',0,48,33,'CM'],['us',0,46,38,'CM']],ball:[25,15],
 o:[['Sprint at the center back too',0,[38,32,27,17],"Two of you on one man looks brave. But you leave their DM completely free, and one pass beats both of you."],
    ['Jump tight onto their DM',2,[38,32,34,27],"Your striker is already pressing the ball and cutting off the other center back. That leaves one easy pass: into their DM. Get tight on him and the center back has nothing on except a long ball."],
    ['Drop back into your midfield line',1,[38,32,38,41],"Solid, and right if your striker wasn't pressing. Here it just lets them play out through the middle."]],pro:1},
{cat:'move',role:'NUMBER 10',min:"33'",sc:'1-0',q:"Your right winger has reached the byline and is about to cut it back.",
 p:[['gk','them',34,2,'GK'],['us',0,60,3,'W'],['them',0,56,6,'FB'],['them',0,29,7,'CB'],['them',0,39,7,'CB'],['us',0,32,8.5,'ST'],['them',0,36,12,'DM'],['me',0,36,21,''],['them',0,25,23,'CM']],ball:[59,4],
 o:[['Stop at the top of the box for the pull-back',2,[36,21,42,17],"Look at their DM: he's dropped onto the penalty spot. Run there and you're running into him. Stay at the top of the box and the cut-back comes to you with time to shoot."],
    ['Arrive at the penalty spot',1,[36,21,37,11],"Usually the best spot for a cut-back. But their DM is already standing on it, so the ball ends up with him."],
    ['Run to the near post',0,[36,21,46,5],"Their full-back and your winger are already there. You'd block your own cut-back lane."]],pro:0},
{cat:'hold',role:'NUMBER 10',min:"47'",sc:'0-0',q:"Your center back plays it into your feet. You have your back to goal.",
 p:[['gk','them',34,3,'GK'],['me',0,36,30,''],['them',0,34.5,27.5,'CM'],['them',0,22,31,'CM'],['us',0,28,44,'CM'],['them',0,29,40,'CM'],['them',0,28,18,'CB'],['them',0,40,18,'CB'],['us',0,34,19,'ST'],['us',0,36,54,'CB']],pass:[36,53,36,31.5],
 o:[['Lay it off to your midfielder',1,[36,30,28.5,43],"Not wrong, but their midfielder is only a few metres from him. You pass the pressure on instead of beating it."],
    ['Shield it and wait for help',0,[36,30,36,31],"He's right on you, and the longer you wait the more of them arrive. Holding only works when help is close."],
    ['Roll him on your right side',2,[36,30,43,23],"Look where he's standing: tight on your left shoulder, and there's nobody covering on your right. Let it run across you and spin that way. From my notes on Foden: turn the defender yourself and you gain loads of space to run into."]],pro:2},
{cat:'move',role:'NUMBER 10',min:"58'",sc:'2-2',q:"Your midfielder has the ball just inside their half, facing forward.",
 p:[['gk','them',34,4,'GK'],['me',0,40,28,''],['them',0,37,31,'DM'],['them',0,28,21,'CB'],['them',0,40,21,'CB'],['them',0,16,22,'FB'],['them',0,54,23,'FB'],['us',0,34,22,'ST'],['us',0,30,46,'CM'],['them',0,26,40,'CM']],ball:[31,45],
 o:[['Check short to get it to feet',1,[40,28,37,36],"Their DM is right next to you. You'd get it under pressure, facing your own goal."],
    ['Run beyond your striker, in behind',2,[40,28,44,8],"Look how high their back line is: there are almost 20 metres behind it, and your midfielder is facing forward with time. Their DM won't follow you that far. Go now while you're still onside."],
    ['Drift wide to the right',0,[40,28,55,30],"Their full-back is already there and the pass gets slower. You take yourself out of the most dangerous space."]],pro:1},
{cat:'counter',role:'NUMBER 10',min:"65'",sc:'0-0',q:"You win the ball back in your own half. Their team was attacking.",
 p:[['me',0,34,58,''],['them',0,30,62,'CM'],['them',0,42,63,'CM'],['them',0,28,36,'CB'],['them',0,41,37,'CB'],['them',0,14,45,'FB'],['us',0,10,48,'W'],['us',0,46,44,'ST']],ball:[34,56.8],
 o:[['Carry it forward into the space',2,[34,58,33,44],"Look ahead: 20 metres of open grass, and their center backs are backing off. Run at them and they have to decide who steps out. From my notes: don't get rid of it too fast when you have space to drive forward."],
    ['Play it early to your left winger',1,[34,58,11,47],"A good habit on the counter, but their full-back is right next to him. He'll take it under pressure and the break slows down."],
    ['Hit a long ball in behind for your striker',0,[34,58,40,32],"Too early and too long. Both center backs are still between him and goal, so the keeper or a defender gets there first."]],pro:0},
{cat:'setp',role:'NUMBER 10',min:"74'",sc:'1-1',q:"Your corner gets headed out. It drops to you at the edge of the box.",
 p:[['gk','them',34,2,'GK'],['me',0,30,21,''],['them',0,24,17,'CM'],['them',0,27,8,'CB'],['them',0,38,7,'CB'],['us',0,32.5,8,'CB'],['them',0,42,12,'CM'],['us',0,21,10,'ST'],['them',0,18,13,'FB'],['us',0,55,23,'FB']],pass:[28,9.5,30,19.5],
 o:[['Hit it first time',1,[30,21,33,-0.5],"Sometimes it flies in. Here their player is already sprinting out at you and there are five bodies in the way. Probably blocked."],
    ['Take a touch and shoot',0,[30,21,26,19],"The touch gives their player the second he needs to block you, and the box is still full."],
    ['Play it out to your free full-back',2,[30,21,54,22.5],"Look right: your full-back is alone outside the box. Keep the ball, and he can cross it straight back in while all their players are still deep in their own box."]],pro:2},
{cat:'state',role:'NUMBER 10',min:"87'",sc:'1-0',q:"You get the ball in their half. Your teammates are running forward.",
 p:[['gk','them',34,3,'GK'],['me',0,38,30,''],['them',0,36,34,'CM'],['us',0,34,18,'ST'],['them',0,30,16,'CB'],['them',0,40,16,'CB'],['them',0,16,18,'FB'],['them',0,54,18,'FB'],['us',0,60,30,'W']],ball:[39,29],
 o:[['Thread it through to your striker',0,[38,30,35,10],"Two center backs are on him. If it's cut out, they break against you with three minutes left."],
    ['Take it towards their corner and keep it with your winger',2,[38,30,58,18],"Look at the clock and the score: 1-0, 87 minutes. Only you and your striker are up against four defenders. Keep the ball near their corner, win a throw or a foul, and the clock runs down."],
    ['Shoot from 30 metres',1,[38,30,35,-0.5],"It's not a disaster, it goes out for a goal kick at worst. But you hand them the ball back when you could keep it."]],pro:1},
{g:'your goal',cat:'track',role:'NUMBER 10',min:"60'",sc:'1-0',q:"They're breaking after winning the ball. You're sprinting back.",
 p:[['gk','us',34,2,'GK'],['them',0,36,47,'CM'],['me',0,30,55,''],['them',0,23,51,'10'],['us',0,37,40,'CM'],['us',0,48,42,'CM'],['us',0,28,26,'CB'],['us',0,40,26,'CB'],['them',0,34,23,'ST'],['them',0,58,36,'W'],['us',0,56,30,'FB']],ball:[36,45.6],
 o:[['Sprint to track their runner on the left',2,[30,55,23,40],"Look at their 10: he's free, and your midfielder has stepped up to the ball, leaving a big gap on your left. Get to that runner before the pass does."],
    ['Chase the ball carrier from behind',1,[30,55,35,48],"You might nick it back, and your midfielder is already facing him. But if he plays it sideways, their 10 has all that space."],
    ['Get back into the middle behind the ball',0,[30,55,34,44],"Right area, but you'd be ball-watching. Their free runner arrives in the gap and nobody has him."]],pro:0}
];
