// NEW CATS: screen:'Screening & protecting', press:'Pressing triggers', foul:'Tactical fouls', setp:'Set pieces'
QS2.mid=[
{cat:'build',role:'DEFENSIVE MIDFIELDER',min:"10'",sc:'0-0',q:"Your left center back has the ball. Their front players are pressing your back line.",
 p:[['me',0,34,62,''],['them',0,35,58,'10'],['them',0,28,74,'ST'],['them',0,40,74,'ST'],['us',0,22,80,'CB'],['us',0,46,80,'CB'],['us',0,6,70,'FB'],['us',0,62,70,'FB'],['them',0,22,58,'CM']],ball:[23.2,78.8],
 o:[["Stay in midfield and show for the pass",0,[34,62,30,67],"Their 10 is right on your back and their striker can step into the lane. You'd receive facing your own goal with no way to turn."],
    ["Drop between your center backs",2,[34,62,34,80],"Look at the back: their two strikers against your two center backs. Drop in between and it's 3v2, so one of you is always free to carry it forward."],
    ["Push higher to drag their 10 away",1,[34,62,34,52],"It can open space, but it doesn't fix the problem. Your center backs are still 2v2 against their strikers."]],pro:1},
{g:'your goal',cat:'screen',role:'DEFENSIVE MIDFIELDER',min:"55'",sc:'1-1',q:"Their midfielder has the ball in front of you. Your other midfielder is going to close him.",
 p:[['gk','us',34,2,'GK'],['us',0,27,18,'CB'],['us',0,41,18,'CB'],['us',0,56,21,'FB'],['them',0,34,19.5,'ST'],['me',0,34,31,''],['them',0,41,27,'10'],['them',0,32,46,'CM'],['us',0,33,39,'CM'],['them',0,58,33,'W']],ball:[32,44.6],run:[33,39,32,43],
 o:[["Hold your spot between the ball and their 10",2,[34,31,38.5,34],"Your teammate is already pressing the ball. Look at their 10, sitting in the gap in front of your center backs. Stay in the passing lane and that pass never arrives."],
    ["Jump out and press the ball too",0,[34,31,32,43],"Two of you on one player, and their 10 is free behind you both. One pass and he's turning at your back line."],
    ["Drop into your back line",1,[34,31,34,21],"Your back line is safer, but now their 10 gets the ball in front of you with time to turn and pick a pass."]],pro:0},
{cat:'press',role:'CENTRAL MIDFIELDER',min:"25'",sc:'0-0',q:"Their right back passes it back to his center back. Your striker goes to press.",
 p:[['gk','them',34,2,'GK'],['them',0,26,16,'CB'],['them',0,44,17,'CB'],['them',0,60,28,'FB'],['us',0,58,37,'W'],['us',0,36,24,'ST'],['them',0,35,31,'DM'],['me',0,41,42,''],['us',0,26,42,'CM'],['them',0,22,34,'CM']],pass:[60,28,45.5,18],run:[36,24,42,19],
 o:[["Hold your spot in the midfield line",1,[41,42,39,40],"Fine if nobody is pressing. But your striker has gone, and if their DM stays free he just plays through the press."],
    ["Sprint at the center back with your striker",0,[41,42,45,24],"Your striker already has him. Two on the center back leaves their DM free for an easy way out."],
    ["Jump onto their DM while the ball travels back",2,[41,42,36,33],"A back pass is your signal to go. Look at your striker: he's curving in to cut off the other center back, so their DM is the only way out. Get tight on him while the ball is still rolling."]],pro:2},
{cat:'cover',role:'DEFENSIVE MIDFIELDER',min:"65'",sc:'1-1',q:"Your right winger has the ball. Your right back has gone past him on the overlap.",
 p:[['us',0,56,26,'W'],['them',0,58,21,'FB'],['us',0,60,32,'FB'],['them',0,40,38,'CM'],['us',0,24,40,'CM'],['me',0,36,48,''],['them',0,60,54,'W'],['them',0,32,62,'ST'],['us',0,26,70,'CB'],['us',0,42,70,'CB']],ball:[55,24.8],run:[60,32,64,16],
 o:[["Push up to the edge of the box for a cut-back",0,[36,48,38,22],"You'd add a body in the box, but if the move breaks down nobody is in front of your back line."],
    ["Shift across into the space your right back left",2,[36,48,52,57],"Look at their winger: still standing high on your right with nobody near him. Lose the ball now and one pass puts him running at your center back. Fill that space."],
    ["Stay central in front of your center backs",1,[36,48,35,53],"Normally a good spot. But your center backs can handle their striker, and their winger is completely free on your right."]],pro:1},
{cat:'pass',role:'CENTRAL MIDFIELDER',min:"20'",sc:'0-0',q:"You get the ball on the left of midfield. Their midfielder is closing you down.",
 p:[['me',0,26,46,''],['them',0,29,42,'CM'],['us',0,8,50,'FB'],['them',0,10,38,'W'],['us',0,28,30,'ST'],['them',0,28,26.5,'CB'],['them',0,42,23,'CB'],['them',0,33,36,'CM'],['us',0,47,42,'CM']],ball:[26.2,44.6],run:[47,42,40,27],
 o:[["Play it into your striker so he can set it for the runner",2,[26,46,27.5,31.5],"Look at their other midfielder: he's standing right in the lane to your runner. The lane to your striker is open. He lays it off first time and your teammate arrives on it facing goal."],
    ["Play it back to your left back",1,[26,46,9,49.5],"Safe, and fine if nothing is on. But you'd miss a run that's already happening."],
    ["Hit it straight into the runner's path",0,[26,46,40,28],"Their midfielder is in the way. That pass gets cut out, and you've lost it in the middle."]],pro:0},
{cat:'switchp',role:'CENTRAL MIDFIELDER',min:"40'",sc:'0-0',q:"You have the ball on the left of midfield. Your right winger is wide on the far side.",
 p:[['me',0,28,46,''],['them',0,30,41,'CM'],['them',0,40,40,'CM'],['us',0,62,30,'W'],['them',0,61,27.5,'FB'],['them',0,24,60,'ST'],['us',0,22,66,'CB'],['us',0,42,66,'CB'],['us',0,60,60,'FB']],ball:[28.6,44.7],
 o:[["Hit the long switch to your right winger",1,[28,46,61,31],"The right idea when he's free. Here their full-back is right on him, and a long ball in the air gives him time to step in front."],
    ["Turn and carry it forward",0,[28,46,31,35],"Two of their midfielders are squeezing you. That's how you lose it in the middle of the pitch."],
    ["Recycle it to your right center back",2,[28,46,41,65],"Look at their full-back: tight on your winger. Your center back has nobody within 15 metres and your right back is free next to him. Two short passes on the ground get it to the far side safely."]],pro:2},
{cat:'move',role:'CENTRAL MIDFIELDER',min:"78'",sc:'0-1',q:"Your left winger is about to cross. You're arriving from midfield.",
 p:[['gk','them',33,2,'GK'],['us',0,7,12,'W'],['them',0,11,15,'FB'],['us',0,30,14,'ST'],['them',0,29,8.5,'CB'],['them',0,38,8,'CB'],['us',0,45,10,'W'],['them',0,48,7,'FB'],['them',0,42,19,'CM'],['me',0,32,28,'']],ball:[8.2,12.4],run:[30,14,27,6],
 o:[["Arrive late around the penalty spot",2,[32,28,33,12],"Your striker is attacking the near post and your other winger is at the far post. Look at the penalty spot: nobody's there, and their midfielder is watching the ball. Time your run to arrive as the cross does."],
    ["Sprint to the near post",0,[32,28,26,7],"Your striker is already going there. Two of you in the same space makes it easy for one defender."],
    ["Wait at the edge for the second ball",1,[32,28,30,20],"A good job when you're level or winning. Losing late, you need another body in the box."]],pro:0},
{cat:'react',role:'CENTRAL MIDFIELDER',min:"30'",sc:'0-0',q:"Your winger loses the ball near the right touchline in their half. Their full-back wins it.",
 p:[['gk','them',34,2,'GK'],['them',0,46,16,'CB'],['them',0,60,30,'FB'],['us',0,63,36,'W'],['us',0,56,22,'ST'],['me',0,53,35,''],['them',0,44,28,'CM'],['us',0,44,33,'CM'],['them',0,64,50,'W']],ball:[59,31.2],
 o:[["Drop back into your midfield spot",1,[53,35,44,48],"The safe choice when you're alone or far from the ball. Here you're five metres away with help around you."],
    ["Close him down right now",2,[53,35,58.5,32],"Look around him: the touchline on one side, your winger and striker within a few metres, and their midfielder is marked. Three of you, one of him. Win it now and you're already in their half."],
    ["Run back to track their winger",0,[53,35,62,49],"Your winger blocks the pass down the line. Turning your back on the ball lets their full-back walk out of trouble."]],pro:1},
{cat:'state',role:'DEFENSIVE MIDFIELDER',min:"88'",sc:'0-1',q:"You have the ball in midfield. 0-1 down, two minutes left.",
 p:[['gk','them',34,2,'GK'],['them',0,28,12.5,'CB'],['them',0,40,12.5,'CB'],['us',0,30,15.5,'ST'],['us',0,38,15.5,'CB'],['them',0,42,27,'CM'],['us',0,7,31,'W'],['them',0,9,27,'FB'],['them',0,12,35,'W'],['me',0,34,42,'']],ball:[34,40.6],
 o:[["Play it out wide to your winger",1,[34,42,8,32],"Wide is often the way through a deep defence. But look: he's got two defenders on him, and the clock is running."],
    ["Keep it and recycle across the back",0,[34,42,48,50],"That's what you do when you're winning. Down a goal with two minutes left, passing sideways helps them."],
    ["Clip it into the box for your striker and center back",2,[34,42,34,14],"Look at the box: your center back has gone up, so it's 2v2 against their center backs. With two minutes left, get the ball where your big players are and fight for the second ball."]],pro:2},
{g:'your goal',cat:'foul',role:'DEFENSIVE MIDFIELDER',min:"70'",sc:'1-0',q:"You lose the ball in their half. Their midfielder breaks past you at the halfway line.",
 p:[['gk','us',34,2,'GK'],['us',0,27,28,'CB'],['us',0,41,28,'CB'],['them',0,12,44,'W'],['them',0,56,42,'W'],['them',0,33,50,'CM'],['me',0,39,54.5,''],['us',0,6,62,'FB'],['us',0,62,63,'FB']],ball:[33,48.6],run:[56,42,50,32],
 o:[["Pull him back now and take the yellow",2,[39,54.5,34.5,50.5],"Look behind you: both full-backs are stranded up the pitch and it's 3v2 against your center backs. He's already past you. It costs you a yellow card and gives them a free kick on halfway. If you're already on a yellow, don't do it."],
    ["Sprint back toward your goal to help",1,[39,54.5,37,36],"Right if you could get there first. But he's running with the ball facing forward, and it's 3v2 before you arrive."],
    ["Chase him and slide in from behind",0,[39,54.5,33.5,46.5],"A slide from behind at full speed is how you get a red card, or give away a free kick much closer to your goal."]],pro:0},
{cat:'build',role:'DEFENSIVE MIDFIELDER',min:"12'",sc:'0-0',q:"You get the ball deep in your own half. They're pressing high.",
 p:[['me',0,34,72,''],['them',0,38,68,'ST'],['them',0,26,63,'CM'],['us',0,20,84,'CB'],['us',0,46,84,'CB'],['them',0,46,79,'W'],['them',0,28,45,'CB'],['them',0,40,45,'CB'],['us',0,34,47,'ST']],ball:[34,70.6],
 o:[["Go long to your striker",1,[34,72,34,48],"Sometimes the right answer under a high press. But their two center backs are on him, so it's a 50/50 at best."],
    ["Lay it back to your left center back",2,[34,72,21,83],"Their striker jumped to you, which left your left center back with nobody near him. Give it to him: he has time to carry it out or pick a pass."],
    ["Turn and dribble out of the press",0,[34,72,30,62],"Their striker is closing from one side and their midfielder from the other. Lose it here and they're through on goal."]],pro:1},
{cat:'setp',role:'DEFENSIVE MIDFIELDER',min:"80'",sc:'1-0',q:"Your team has a corner on the right. Where do you go?",
 p:[['gk','them',34,2,'GK'],['us',0,31,10,'CB'],['them',0,28.5,7,'CB'],['us',0,39,9,'ST'],['them',0,41.5,6,'CB'],['me',0,34,25,''],['them',0,28,47,'ST'],['them',0,41,47,'W'],['us',0,34,55,'CB']],ball:[66.5,1],
 o:[["Go into the box to attack the corner",0,[34,25,35,11],"More bodies in the box can win the header, but it leaves nobody to stop the counter."],
    ["Stand on the edge of the box for the second ball",1,[34,25,34,19],"Often your job on a corner. But if the ball flies over you, you're 30 metres from the action."],
    ["Stay deep with your center back to guard the counter",2,[34,25,36,43],"Look at halfway: their two forwards stayed up against your one center back. 1-0 up with ten minutes left, if they clear it and win it, that's 2v1 at your goal. Make it 2v2."]],pro:2}
];
