// NEW CATS: press:'Pressing from the front', offside:'Timing & the offside line'
QS2.striker=[
{cat:'press',role:'STRIKER',min:"30'",sc:'0-0',q:"Their center back has the ball in his own half. You're the first to press.",
 p:[['gk','them',34,6,'GK'],['them',0,24,28,'CB'],['them',0,44,27,'CB'],['them',0,31,39,'DM'],['them',0,6,36,'FB'],['me',0,37,36,''],['us',0,11,42,'W'],['us',0,40,47,'CM']],ball:[25,29.2],
 o:[["Sprint straight at him",0,[37,36,26,30],"Look behind you: their DM is free in the middle. Run straight at the center back and he just slips it into the DM, and you're out of the game."],
    ["Curve your run from inside, block the pass into the middle, push him to the touchline",2,[37,36,30,33.5],"Look at their DM, free behind you. Curve your run so your body covers him, and the only pass left is out to the full-back, where your winger is waiting. From my notes on Vardy: he always blocks the pass into the middle and just steers the center back to one side."],
    ["Drop off and mark their DM",1,[37,36,32,38],"Takes the DM away, but the center back gets time to carry it forward or switch to the other center back."]],pro:1},
{cat:'press',role:'STRIKER',min:"65'",sc:'0-0',q:"Their full-back plays it back to their center back. You're the closest to him.",
 p:[['gk','them',34,4,'GK'],['them',0,46,28,'CB'],['them',0,24,26,'CB'],['them',0,60,31,'FB'],['them',0,36,39,'DM'],['me',0,37,32,''],['us',0,56,39,'W'],['us',0,29,42,'10']],ball:[45,24.5],
 o:[["Sprint at him now, curving to cut off the other center back",2,[37,32,43,25],"Look at the ball: it's bounced off his foot, towards his own goal. He has to turn and chase it, so he can't look up. That's the moment. From my notes on Rashford: press the center back when he takes a bad touch or the pass goes backwards."],
    ["Hold your spot and block the pass to the other center back",1,[37,32,34,29],"That's your normal job. But this touch is a gift, and if you wait he gets the ball under control and plays."],
    ["Wait for your midfield to push up first",0,[37,32,36,35],"Pressing together is usually right, but this chance lasts a second. By the time they're up, he's tidied it up."]],pro:0},
{cat:'move',role:'STRIKER',min:"55'",sc:'0-1',q:"Your right winger has reached the byline inside the box. You're running in.",
 p:[['gk','them',37,1.5,'GK'],['them',0,39,4,'CB'],['them',0,30,5,'CB'],['them',0,61,7,'FB'],['us',0,60,3,'W'],['me',0,35,10,''],['them',0,24,21,'CM'],['us',0,30,24,'CM']],ball:[58.8,3.5],
 o:[["Keep going, attack the near post",1,[35,10,38.5,2.5],"Usually a good run, but look at the near post: both center backs and the keeper are packed in there. The ball has to get past three of them."],
    ["Run across to the far post",0,[35,10,28,3],"A pull-back from the byline won't get past those bodies to the far post. Even if it does, it's a tight angle."],
    ["Stop and drop back towards the penalty spot",2,[35,10,33,15.5],"Look at the space between their center backs and the edge of the box: empty. They've all dropped onto the goal line. Pull back, and the cut-back finds you facing goal with time."]],pro:2},
{cat:'offside',role:'STRIKER',min:"20'",sc:'0-0',q:"Your run in behind didn't get the ball. You're now behind their back line.",
 p:[['gk','them',34,3,'GK'],['me',0,36,11,''],['them',0,28,18,'CB'],['them',0,40,18,'CB'],['them',0,14,19,'FB'],['them',0,54,19,'FB'],['them',0,36,40.5,'CM'],['us',0,34,43,'CM']],ball:[33.4,44.3],
 o:[["Sprint back onside right now",1,[36,11,36,21],"You're onside, but now you're standing still in front of them and they're all watching you."],
    ["Drift back slowly on their blind side, then go when your midfielder turns",2,[36,11,47,19],"Look at your midfielder: back to goal with a man on him. No pass is coming yet, so you have time. From my notes on Ronaldo: he doesn't rush back from offside. He lets the defence forget him, gets back onside, then gets the ball free."],
    ["Stay where you are and call for it",0,[36,11,35,9],"You're offside. Any pass to you is a free kick for them."]],pro:1},
{cat:'onev',role:'STRIKER',min:"75'",sc:'1-1',q:"You've got in down the right side of the box. The keeper is coming across.",
 p:[['gk','them',37.5,2.5,'GK'],['me',0,51,8,''],['them',0,55,12,'CB'],['them',0,28,7,'CB'],['us',0,25,9,'W'],['us',0,36,16,'10'],['them',0,22,22,'CM']],ball:[50,7],
 o:[["Shoot at the near post",0,[51,8,37.5,0],"Look at the keeper: he's sitting on his near post. From this angle there's almost nothing to aim at."],
    ["Lift it over him towards the far post",1,[51,8,31,-0.5],"It can go in, but from this tight angle it's a hard finish, and their center back is covering the far post."],
    ["Cut it back to your 10 at the penalty spot",2,[51,8,36,15],"Look at the penalty spot: your 10 is arriving and nobody's picked him up. The keeper is stuck at his near post, so your 10 has most of the goal to aim at."]],pro:2},
{cat:'state',role:'STRIKER',min:"86'",sc:'1-0',q:"You're 1-0 up. You win the ball back near their box.",
 p:[['gk','them',34,3.5,'GK'],['me',0,36,15,''],['them',0,40,19,'CB'],['them',0,21,12,'CB'],['them',0,53,17,'FB'],['us',0,55,28,'W'],['them',0,30,26,'CM']],ball:[35.4,13.8],
 o:[["Shoot low, now",2,[36,15,32,-0.5],"Look in front of you: nobody between you and the keeper, and you're 15 metres out. Running down the clock is for when nothing's on. A goal here ends the game."],
    ["Take it to the corner flag and shield it",1,[36,15,63,3],"Right when there's no chance. Here you'd be throwing away a clean shot to kill the game."],
    ["Wait for your winger and give it to him",0,[36,15,54,27],"By the time he gets there, their center back is back on you and the chance is gone."]],pro:0},
{cat:'finish',role:'STRIKER',min:"40'",sc:'0-0',q:"Your right winger crosses. You're arriving to head it.",
 p:[['gk','them',31.5,2,'GK'],['me',0,31,8,''],['them',0,28,11,'CB'],['them',0,41,6,'CB'],['them',0,22,8,'FB'],['us',0,34,16,'10'],['them',0,37,18,'CM'],['us',0,61,17,'W']],pass:[60,16,31.5,7.5],
 o:[["Head it on into the far corner",0,[31,8,31,-0.5],"Look at the keeper: he's moved across with the cross and is standing right by that post."],
    ["Head it down, back the way it came, towards the near post",2,[31,8,37,-0.5],"The keeper followed the ball across, so the side it came from is open. Head it down so it bounces: those are the hardest headers to save."],
    ["Knock it down for your 10",1,[31,8,34,15],"Keeps the move alive, but their midfielder is right with him, and you're already in the best spot to score."]],pro:1},
{cat:'hold',role:'STRIKER',min:"30'",sc:'0-0',q:"A through ball into the right channel. You get there, but their center back gets back too.",
 p:[['gk','them',34,3,'GK'],['me',0,52,22,''],['them',0,51,18.5,'CB'],['them',0,35,14,'CB'],['us',0,60,34,'W'],['us',0,40,34,'CM'],['them',0,40,29,'DM']],ball:[52.5,20.7],run:[60,34,62,20],
 o:[["Shield it, then slip your winger round the outside",2,[52,22,62,13],"Look behind you: your winger is flying up the line. Their center back is goal-side with cover inside, so turning won't work. Hold him off, then play the winger round him."],
    ["Cut inside and shoot",0,[52,22,42,15],"Their center back is goal-side and the other one is covering the middle. You'd be shooting through two bodies."],
    ["Lay it back to your midfielder",1,[52,22,41,32],"Keeps the ball, but their DM is close to him, and you give up the position you just won."]],pro:0},
{cat:'pass',role:'STRIKER',min:"70'",sc:'1-1',q:"Counter attack, 3 against 2. You're carrying the ball through the middle.",
 p:[['gk','them',34,4,'GK'],['me',0,34,34,''],['us',0,14,32,'W'],['us',0,55,34,'W'],['them',0,35,27,'CB'],['them',0,23,22,'CB'],['them',0,30,45,'CM']],ball:[34,32.6],run:[55,34,53,22],
 o:[["Drive into the gap between them",1,[34,34,29,24],"Usually right in a 3v2, to drag both defenders in. But one has already come to you. Dribbling into him just gives the other one time to get across."],
    ["Slip your left winger in",0,[34,34,16,22],"Look where their other center back is: right in that lane."],
    ["Play your right winger in now",2,[34,34,52,20],"Look at their center back: he's already stepped up to you, and nobody is on your right winger. Play it into his run now and he's in on goal."]],pro:2},
{cat:'shoot',role:'STRIKER',min:"60'",sc:'0-1',q:"You receive just outside their box, facing goal.",
 p:[['gk','them',34,3,'GK'],['me',0,37,20,''],['them',0,40,12,'CB'],['them',0,27,12,'CB'],['them',0,51,14,'FB'],['us',0,27,26,'CM'],['them',0,30,23,'DM']],ball:[37,18.7],
 o:[["Lay it off to your midfielder",0,[37,20,28,25.5],"Their midfielder is tracking him step for step. The lay-off just hands them a chance to block."],
    ["Shoot low, now",2,[37,20,31.5,-0.5],"Look at their center back: he's sitting off you, about 8 metres away, and not coming. That's a free shot. Low and on target into the corner."],
    ["Dribble at the center back to get closer",1,[37,20,39,14],"You get closer, but you give him the chance to close you down and block it. The shot is on right now."]],pro:1},
{cat:'offside',role:'STRIKER',min:"50'",sc:'2-2',q:"Your teammate is about to whip in a free kick from the left. You're lined up with their defenders.",
 p:[['gk','them',34,3,'GK'],['us',0,9,27.5,''],['them',0,16.5,20,''],['them',0,22,16,'CB'],['them',0,30,16,'CB'],['them',0,39,16,'CM'],['them',0,47,16,'FB'],['me',0,34.5,16.6,''],['us',0,26,16.6,'CB'],['us',0,43,16.6,'CB']],ball:[10,26],
 o:[["Stay level with their line, then sprint as he strikes it",2,[34.5,16.6,31,6],"Look at their line: they're holding it high, right on the edge of the box. All the space is behind them, in front of the keeper. Go on the strike and you're attacking that space at full speed while they're still turning."],
    ["Get a head start into the space before he kicks it",0,[34.5,16.6,35,10],"Their line is holding high. Go early and you're offside the moment he strikes it."],
    ["Hang back at the edge for the second ball",1,[34.5,16.6,34,24],"Someone should cover it, but that takes your best header threat out of the box."]],pro:0},
{cat:'react',role:'STRIKER',min:"15'",sc:'0-0',q:"Their midfielder takes the ball off you in their half.",
 p:[['gk','them',34,4,'GK'],['me',0,34,26.5,''],['them',0,36,32.5,'CM'],['us',0,41,37,'10'],['us',0,31,38,'CM'],['them',0,55,30,'FB'],['them',0,22,36,'CM'],['them',0,40,20,'CB']],ball:[36.6,33.6],
 o:[["Drop back into shape",1,[34,26.5,33,36],"Fine if you're on your own. But look: two teammates are right around the ball."],
    ["Stay high, ready for when you win it back",0,[34,26.5,37,19],"If they get out of this, your team is one player short behind the ball."],
    ["Press him straight away, from behind",2,[34,26.5,35.6,31],"Look: your 10 and your midfielder are right in front of him, so his forward pass is blocked. Press from behind now and he's trapped between three of you. The first few seconds after losing it are the best time to win it back."]],pro:2}
];
