// NEW CATS: press:'Pressing from the front', counter:'Counter-attacks', setp:'Set pieces & throw-ins'
QS2.winger=[
{cat:'pass',role:'LEFT WINGER',min:"25'",sc:'0-0',q:"You have the ball on the left, about 30 metres from goal. Your full-back is overlapping.",
 p:[['gk','them',34,2,'GK'],['me',0,10,28,''],['them',0,12,22,'FB'],['them',0,24,11,'CB'],['them',0,34,10,'CB'],['them',0,24,26,'CM'],['them',0,20,41,'W'],['us',0,6,42,'FB'],['us',0,30,14,'ST']],ball:[10.4,26.7],run:[6,42,4,20],
 o:[['Slide it down the line, into the space ahead of him',2,[10,28,4,12],"Their winger didn\'t track him, so he\'s free, and their full-back is stuck facing you. Play it in front of him. From my notes on Luis Díaz: play the overlap so he can cross first time with his body facing forward, not behind him so he has to stop."],
    ['Play it to his feet as he goes past',1,[10,28,5,32],"He\'s free, but now he has to stop the ball, and their full-back gets time to turn and close him down."],
    ['Take their full-back on down the line yourself',0,[10,28,6,14],"You\'d run into the same lane your full-back is using. Two of you in one channel, and their full-back only has to block one."]],pro:0},
{cat:'move',role:'RIGHT WINGER',min:"35'",sc:'0-0',q:"Your full-back has the ball on the right touchline. You\'re ahead of him, out on the line.",
 p:[['gk','them',34,2,'GK'],['me',0,64,30,''],['them',0,64,25,'FB'],['them',0,45,14,'CB'],['them',0,34,13,'CB'],['us',0,39,17,'ST'],['them',0,46,34,'CM'],['them',0,58,44,'W'],['us',0,63,48,'FB']],ball:[62.5,46.8],
 o:[['Show for it to feet',0,[64,30,63,37],"Their full-back is right behind you. You get it with your back to goal against the line, and their winger is closing in too."],
    ['Run inside him, into the gap before their center back',2,[64,30,54,14],"Look at the gap: their full-back is out on the line with you, and their center back is held by your striker. That channel is empty, and your full-back can slide it in."],
    ['Spin down the line, behind him',1,[64,30,66,10],"Good run when he\'s tight on your inside. Here he\'s standing on the line, so he\'s already goal-side of it."]],pro:1},
{cat:'shape',role:'LEFT WINGER',min:"50'",sc:'1-0',q:"Your midfielder switches the play out to you on the left. The ball is in the air.",
 p:[['gk','them',34,2,'GK'],['me',0,5,36,''],['them',0,16,30,'FB'],['them',0,26,14,'CB'],['them',0,37,14,'CB'],['them',0,28,33,'CM'],['us',0,32,19,'ST'],['us',0,54,42,'CM'],['them',0,49,37,'CM']],pass:[54,42,6,35.5],
 o:[['First touch inside, towards the box',0,[5,36,12,30],"Their full-back is coming from inside. A touch inside takes the ball straight into him."],
    ['First touch forward, down the line',2,[5,36,5,22],"Look where their full-back is coming from: inside, at an angle, on the run. A first touch into the space down the line takes you past him before he can stop and set himself."],
    ['Control it dead, then decide',1,[5,36,5,37.5],"Safe, but he\'s sprinting at you. By the time you look up, he\'s set and can show you wherever he wants."]],pro:1},
{cat:'move',role:'RIGHT WINGER',min:"75'",sc:'1-1',q:"Your left winger is about to cross from the other side. You\'re wide on the right.",
 p:[['gk','them',31,2,'GK'],['us',0,6,9,'W'],['them',0,10,14,'FB'],['them',0,30,8,'CB'],['them',0,37,9,'CB'],['us',0,33,11.5,'ST'],['them',0,46,15,'FB'],['them',0,36,21,'CM'],['me',0,59,20,'']],ball:[7.4,9.6],
 o:[['Run to the far post, behind their full-back',2,[59,20,40,4],"Their full-back has tucked in and is watching the ball, so he can\'t see you. Arrive behind his back. From my notes on Sterling: on a cross from the other side, run to the far post so the defender loses you. If the lane closes, drift back towards the penalty spot."],
    ['Stay wide for a switch or a second ball',0,[59,20,63,22],"Nobody is going to cross it out to the touchline. If the ball goes into the box and you\'re out here, you\'re not part of the chance."],
    ['Edge of the box for a cut-back',1,[59,20,45,22],"A fair option, but their midfielder is already guarding that area, and your winger is crossing, not cutting it back."]],pro:0},
{cat:'press',role:'RIGHT WINGER',min:"15'",sc:'0-0',q:"They\'re building from the back. Their center back on your side has the ball.",
 p:[['gk','them',34,3,'GK'],['them',0,45,10,'CB'],['them',0,23,10,'CB'],['them',0,63,17,'FB'],['them',0,38,24,'CM'],['us',0,38,30,'CM'],['us',0,33,17,'ST'],['me',0,57,26,'']],ball:[44.5,11.4],
 o:[['Sprint straight at the center back',1,[57,26,46,12.5],"Brave, but a straight line leaves the full-back free behind you. One pass and they\'re out of your press."],
    ['Curve your run from outside, blocking the pass to the full-back',2,[57,26,54,14],"Look at his options: your midfielder has their CM, so the only easy pass is out to the full-back. Curve your run to cut that lane while you close him. From my notes on Di María: when you press the center back, close off the full-back on the run, or they get out of the press easily."],
    ['Stay with their full-back',0,[57,26,61.5,19.5],"Now nobody is pressing the ball. The center back has all the time he wants to step in and pick a pass."]],pro:1},
{cat:'counter',role:'RIGHT WINGER',min:"30'",sc:'0-0',q:"Your team has just won the ball. It\'s at your feet, just inside their half.",
 p:[['me',0,54,49,''],['them',0,59,57,'FB'],['them',0,43,55,'CM'],['them',0,43,31,'CB'],['them',0,31,32,'CB'],['them',0,15,35,'FB'],['us',0,36,41,'ST'],['us',0,40,60,'CM']],ball:[53.6,47.6],
 o:[['Pass into your striker\'s feet',1,[54,49,37,42],"Not bad, but he has two center backs in front of him and his back to goal. It slows the attack down."],
    ['Hold it up and wait for support',0,[54,49,55,51],"Look behind you: their full-back and midfielder are already out of the game. Wait, and they get back."],
    ['Drive into the space in front of you',2,[54,49,53,34],"Look at their full-back: he got caught upfield and he\'s behind you now. The whole right side is empty. Carry it at speed and make their center back choose between you and your striker."]],pro:2},
{cat:'cross',role:'LEFT WINGER',min:"30'",sc:'0-0',q:"You have the ball wide on the left, level with the edge of their box.",
 p:[['gk','them',33,2,'GK'],['me',0,7,18,''],['them',0,11,13.5,'FB'],['them',0,30,9,'CB'],['them',0,37,9.5,'CB'],['us',0,33,10,'ST'],['them',0,46,11,'FB'],['them',0,26,25,'CM'],['us',0,21,34,'CM'],['us',0,56,30,'W']],ball:[7.5,16.7],
 o:[['Cross it now for your striker',0,[7,18,33,9],"Look in the box: your striker is alone against two center backs and the keeper. A cross now is a cleared ball, and maybe a counter."],
    ['Cut inside and shoot',1,[7,18,16,18],"From out here, with their full-back and midfielder close, it\'s a low chance. At least it ends with a shot."],
    ['Keep it: play it back and go again when runners arrive',2,[7,18,21,33],"One of yours in the box against two of theirs. Keep the ball, play it back to your midfielder, and cross it when more of your players can attack it."]],pro:2},
{cat:'onev',role:'RIGHT WINGER (LEFT-FOOTED)',min:"40'",sc:'0-0',q:"You\'re 1v1 with their full-back on the right. He\'s showing you inside.",
 p:[['gk','them',34,2,'GK'],['me',0,59,30,''],['them',0,61.5,25.5,'FB'],['them',0,50,24,'CM'],['them',0,44,13,'CB'],['them',0,33,12,'CB'],['us',0,36,17,'ST'],['us',0,48,40,'CM'],['us',0,64,44,'FB']],ball:[58.7,28.6],
 o:[['Play it back to your midfielder and go again',2,[59,30,49,39],"Look inside: their midfielder is waiting right where the full-back is sending you. It\'s a trap. Recycle it, and attack him again once they\'ve shifted."],
    ['Cut inside onto your left foot',0,[59,30,52,25],"That\'s exactly what they want. Their midfielder is already there, and losing it here starts their counter."],
    ['Fake inside, then go outside him',1,[59,30,65,13],"Can work if your fake moves him, but he\'s standing on your outside with the line close. Low odds."]],pro:0},
{cat:'state',role:'LEFT WINGER',min:"88'",sc:'0-1',q:"You\'re 1-0 down with two minutes left. The ball comes to you wide on the left, about 30 metres out.",
 p:[['gk','them',34,2,'GK'],['me',0,8,30,''],['them',0,12,25,'FB'],['them',0,31,8,'CB'],['them',0,38,8,'CB'],['them',0,45,9,'FB'],['us',0,33,11,'ST'],['us',0,40,12.5,'CB'],['us',0,26,13,'10'],['us',0,22,42,'CM']],ball:[8.4,28.7],
 o:[['Whip it in early, now',2,[8,30,34.5,6],"Look at the box: three of yours against three of theirs, and their line has dropped deep near the keeper. Two minutes left and a goal down, a dangerous ball now beats a perfect one later."],
    ['Beat your man and get to the byline first',1,[8,30,5,6],"A cut-back from the byline is a better ball, but it eats time, and their full-back is set to stop it."],
    ['Play it back and keep possession',0,[8,30,21,41],"Keeping the ball doesn\'t help you now. When you\'re losing late, the clock is on their side."]],pro:0},
{g:'your goal',cat:'setp',role:'RIGHT WINGER',min:"60'",sc:'2-1',q:"They have a throw-in on your side, level with the edge of your half.",
 p:[['gk','us',34,2,'GK'],['them',0,67.5,40,'FB'],['them',0,62,30,'W'],['us',0,61,26,'FB'],['them',0,54,49,'CM'],['us',0,52,45,'CM'],['me',0,59,36,''],['them',0,40,22,'ST'],['us',0,40,18,'CB']],ball:[67.8,41.2],
 o:[['Mark the midfielder coming short',1,[59,36,53.5,46],"Your midfielder is already on him. Two of you on one player leaves someone else free."],
    ['Stay tight to the thrower, ready for the return',2,[59,36,65,38],"Look around: their winger and midfielder are both marked. The free man is the thrower himself. He throws it short, steps back on and gets it back down the line. Be next to him."],
    ['Drop and double up on their winger',0,[59,36,62,27],"Your full-back already has him, and your center back is inside. Dropping leaves the thrower free for the one-two."]],pro:1},
{cat:'onev',role:'LEFT WINGER',min:"55'",sc:'1-1',q:"You\'re running at their full-back on the left. Your 10 is level with you, inside.",
 p:[['gk','them',34,2,'GK'],['me',0,8,30,''],['us',0,21,30,'10'],['them',0,15.5,24,'FB'],['them',0,28,13,'CB'],['them',0,38,12,'CB'],['us',0,33,17,'ST'],['them',0,33,32,'CM']],ball:[8.5,28.7],
 o:[['Pass to your 10',0,[8,30,20,30],"Their full-back has already stepped inside to cut that pass. It\'s the one option he\'s covering."],
    ['Drive at him first to commit him',1,[8,30,13,25],"Normally right in a 2v1. Here he\'s already committed to your 10, so waiting just lets him recover."],
    ['Go yourself, down the line',2,[8,30,6,10],"Look where their full-back is standing: inside, guarding the pass to your 10. That leaves the line open, and their center back is far across. Go."]],pro:2},
{cat:'scan',role:'RIGHT WINGER',min:"10'",sc:'0-0',q:"Your center back plays it up to you on the right touchline, near halfway.",
 p:[['me',0,64,50,''],['them',0,63.5,46,'FB'],['us',0,46,66,'CB'],['us',0,51,56,'CM'],['them',0,45,48,'CM'],['them',0,55,64,'W'],['them',0,44,32,'CB'],['them',0,32,32,'CB']],pass:[46,66,63.5,51.3],
 o:[['Turn and go down the line',0,[64,50,66,34],"He\'s right on your back. Turning into him against the line is how you lose it, and then they\'re running at your defence."],
    ['Control it and shield, wait for support',1,[64,50,64.5,52],"Safe enough, but he gets time to press, and their winger can come across and trap you against the line."],
    ['Bounce it first time to your midfielder, then spin in behind',2,[64,50,51.5,55],"Look at your midfielder: free and facing forward. One touch to him and spin, and their full-back is left behind you with space to run into."]],pro:2}
];
