var CATS={state:'Reading the score & clock',scan:'Scanning before the ball',finish:'Finishing',onev:'1v1 decisions',pass:'Seeing the pass',react:'Reacting after losing it',move:'Movement off the ball',cross:'Final ball from wide',shoot:'Shooting choices',hold:'Back to goal',switchp:'Switching the play',shape:'Body shape & receiving',delay:'Defending 1v1 & delaying',line:'Stepping up or dropping',cover:'Covering & clearing',build:'Playing out from the back',aerial:'Defending crosses',track:'Tracking runners'};
/* Real pitch in metres. x: 0 = left touchline, 68 = right touchline. y: 0 = goal line at the top.
   Attacking questions: top = their goal. Defending questions (g:'your goal'): top = your goal.
   p: [team, x, y, label]  team: me | us | them | gk.  ball:[x,y]  pass/run: [x1,y1,x2,y2]  v:[yTop,yBottom] visible range */
var QS={
striker:[
{cat:'finish',role:'STRIKER',min:"60'",sc:'1-1',q:"Your right winger plays it low across the six-yard box. You get there first.",
 p:[['gk','them',37,1.5,'GK'],['me',0,31,6,''],['them',0,33.5,8.5,'CB'],['them',0,27,9.5,'CB'],['them',0,44,6.5,'FB'],['us',0,29,15,'10'],['them',0,31,17,'CM'],['us',0,63,1.5,'W']],ball:[62,2],pass:[63,1.5,32,5.5],
 o:[['Side-foot it first time into the far corner',2,[31,6,31.5,-0.5],"Look at the keeper: he had to cover his near post for the cross, so the far corner is open. First time, inside of the foot, on target. From my notes on Haaland: accuracy, not power."],
    ['Take one touch across the defender, then shoot',1,[31,6,28,5],"Can work, but the center back is right behind you and the keeper gets a second to reset."],
    ['Dummy it for your 10 behind you',0,[31,6,29,15],"Their midfielder is marking your 10. The dummy gives the ball to them."]],pro:0},
{cat:'finish',role:'STRIKER',min:"70'",sc:'0-0',q:"You're through on goal. The keeper comes off his line.",
 p:[['gk','them',35,6.5,'GK'],['me',0,31,15,''],['them',0,33,19.5,'CB'],['them',0,20,20,'FB']],ball:[32,14],
 o:[['Go round the keeper',1,[31,15,22,7],"Works if he dives. But it's slow, and their center back is only a few metres behind you."],
    ['Chip him',0,[31,15,34,-0.5],"He's only 6 metres off his line. A chip needs him much further out, or it lands in his hands."],
    ['Shoot early, low, across him into the far corner',2,[31,15,31,-0.5],"A keeper coming out covers his near post and his body. Early and low across him gives him the least time, before the defender arrives."]],pro:2},
{cat:'move',role:'STRIKER',min:"35'",sc:'0-0',q:"Your right winger is about to cross. Where do you run?",
 p:[['gk','them',35,1.5,'GK'],['me',0,33,19,''],['them',0,32,14,'CB'],['them',0,24,13,'CB'],['them',0,51,9,'FB'],['them',0,35,22.5,'CM'],['us',0,60,11,'W']],ball:[59,11.5],
 o:[['Near post, into the gap between center back and full-back',2,[33,19,44,6],"Look at the gap between their center back and full-back. Arrive in it at full speed and you get in front of your defender. From my notes: lots of striker goals come from a quick run to the near post, just putting it on target."],
    ['Far post, behind everyone',1,[33,19,22,6],"Good for a high cross. Your winger is low and close to goal, so it won't get past the near defenders."],
    ['Hold at the penalty spot for a cut-back',0,[33,19,34,12],"Their midfielder is sitting exactly there. A cut-back goes straight to him."]],pro:0},
{cat:'move',role:'STRIKER',min:"25'",sc:'0-0',q:"Your midfielder has the ball. You're on their last line.",
 p:[['gk','them',34,3,'GK'],['me',0,41,17,''],['them',0,37,16,'CB'],['them',0,28,16,'CB'],['them',0,55,15.5,'FB'],['them',0,13,16,'FB'],['them',0,26,30,'CM'],['them',0,46,30,'CM'],['us',0,35,40,'CM']],ball:[35,38.5],
 o:[['Come short to his feet',1,[41,17,40,30],"Useful when he's under pressure. Look again: nobody is on him. He has time to play forward."],
    ['Sprint straight in behind now',0,[41,17,42,4],"Go before he's looked up and you're offside, or the defender just turns and runs with you."],
    ['Curve across the center back\'s blind side, then go',2,[41,17,33,5],"Nobody's pressing your midfielder, so the pass in behind is on. The center back has to watch the ball, so he can't see you curve behind him. Stay onside, then go the moment your midfielder looks up."]],pro:2},
{cat:'finish',role:'STRIKER',min:"50'",sc:'0-0',q:"Your teammate shoots from outside the box.",
 p:[['gk','them',34,2.5,'GK'],['me',0,29,11,''],['them',0,31,12.5,'CB'],['them',0,38,10,'CB'],['us',0,45,21,'CM'],['them',0,42,24,'CM']],ball:[45,20],pass:[45,21,36,1],
 o:[['Drop back to the edge of the box',0,[29,11,30,20],"Someone should, but not the striker. Your job is in the six-yard box."],
    ['Follow the shot in towards the keeper',2,[29,11,33,4],"From my notes on Haaland: he always keeps his run going and waits for the rebound, and a lot of his goals come that way. The center back is watching the shot. You're already moving."],
    ['Spin out to the back post',1,[29,11,22,4],"Can get a deflection, but most rebounds come back out in front of the keeper."]],pro:1},
{cat:'hold',role:'STRIKER',min:"40'",sc:'0-1',q:"A long ball comes up to you. A center back is right behind you.",
 p:[['gk','them',34,3,'GK'],['me',0,34,26,''],['them',0,34,24,'CB'],['them',0,26,19,'CB'],['them',0,46,20,'FB'],['them',0,26,34,'CM'],['us',0,42,35,'10'],['us',0,18,36,'W']],ball:[34,27.5],pass:[34,56,34,27.5],
 o:[['Turn him on your first touch',0,[34,26,40,20],"He's touching you and the other center back is covering. Turning into that usually means losing it."],
    ['Hold it up and wait for runners',1,[34,26,34,27],"Keeps the ball, but slows the attack. Someone is already arriving."],
    ['Lay it off first time to your 10',2,[34,26,41,34],"Your 10 is arriving facing goal and nobody's on him. One touch and you've beaten the center back's pressure without a duel. Then spin and run."]],pro:2},
{cat:'pass',role:'STRIKER',min:"89'",sc:'0-0',q:"Counter attack. You have the ball, a teammate is with you, one defender back.",
 p:[['gk','them',34,3,'GK'],['me',0,28,31,''],['us',0,50,32,'W'],['them',0,42,22,'CB'],['them',0,20,46,'CM']],ball:[29.5,30],
 o:[['Pass to your teammate',0,[28,31,50,31],"Look where the defender is: he's already moving across to block your teammate. The pass goes straight into his path."],
    ['Drive into the box yourself',2,[28,31,30,16],"He's covering your teammate, so the space is in front of you. Keep going and shoot. If he switches to you, slip it to your teammate."],
    ['Slow down and wait for support',1,[28,31,28,32],"Safe, but in the 89th minute a 2v1 is the chance. Support comes, but so do their defenders."]],pro:1},
{cat:'move',role:'STRIKER',min:"70'",sc:'1-1',q:"Your team has a corner from the right. Where do you set up?",
 p:[['gk','them',33,1.5,'GK'],['me',0,34,15,''],['us',0,68,0,''],['them',0,38,3,'P'],['them',0,40,5,''],['them',0,37,7,''],['us',0,41,6,''],['them',0,30,8,''],['us',0,24,10,'']],ball:[67.5,0.5],
 o:[['Near post, with the crowd',1,[34,15,39,5],"Someone has to attack the near post, but look: three of theirs are already there."],
    ['Middle of the box, then attack the ball',2,[34,15,33,7],"From my notes: Lewandowski stands in the middle of the box and makes his run from there. You can attack the first ball, and you're right there for the second ball."],
    ['Edge of the box for the clearance',0,[34,15,34,20],"That's a midfielder's job. Strikers score inside the six-yard box."]],pro:1}
],
winger:[
{cat:'state',role:'RIGHT WINGER',min:"80'",sc:'1-0',q:"The ball comes to you on the wing. 1-0 up, ten minutes left.",
 p:[['gk','them',34,2,'GK'],['me',0,60,22,''],['them',0,55,18,'FB'],['them',0,59,29,'CM'],['them',0,36,12,'CB'],['them',0,30,11,'CB'],['us',0,33,13,'ST'],['us',0,40,40,'CM']],ball:[61,21],
 o:[['Take it to the corner flag and shield it',2,[60,22,67,1],"1-0 up in the 80th minute, the clock is your teammate. Look at the box: your striker is alone against two center backs. Every second by their corner flag is a second they can't score."],
    ['Cross it into the box',1,[60,22,33,11],"Not wrong if your striker can win it, but here it's one against two. A cleared cross is a counter."],
    ['Cut inside and shoot',0,[60,22,44,16],"Two defenders are closing, and losing it here means a break against you with ten minutes left."]],pro:0},
{cat:'onev',role:'RIGHT WINGER',min:"20'",sc:'0-0',q:"You're 1v1 with their full-back.",
 p:[['gk','them',34,2,'GK'],['me',0,61,31,''],['them',0,59,25,'FB'],['them',0,40,14,'CB'],['them',0,28,14,'CB'],['them',0,45,25,'CM'],['us',0,32,18,'ST'],['us',0,63,47,'FB']],ball:[61,29.8],
 o:[['Cut inside onto your other foot',1,[61,31,49,24],"Good when he's showing you outside. But look inside: their midfielder is covering that space."],
    ['Knock it past him down the line and run',2,[61,31,65,8],"Their center back is miles away, so there's 20 metres of space behind the full-back. One touch past him and race. From my notes on Vinícius: stay wide, then go."],
    ['Wait for your full-back to overlap',0,[61,31,61,32],"Your full-back is 16 metres behind. By the time he arrives, their midfielder has come across to help."]],pro:1},
{cat:'cross',role:'RIGHT WINGER',min:"30'",sc:'0-0',q:"You've beaten your man and reached the byline.",
 p:[['gk','them',36,1.5,'GK'],['me',0,63,3,''],['them',0,40,4,'CB'],['them',0,33,5,'CB'],['us',0,38,5.5,'ST'],['them',0,25,7,'FB'],['us',0,33,14,'10'],['them',0,45,17,'CM']],ball:[62,3.5],
 o:[['Float it to the far post',1,[63,3,24,4],"Works with a tall target at the far post. Here their full-back is the only one there."],
    ['Cut it back to the penalty spot',2,[63,3,33,13],"Their defenders are running towards their own goal and are marking your striker. Your 10 is arriving behind them, unmarked, facing goal."],
    ['Drill it hard across the six-yard box',1,[63,3,30,3],"Dangerous ball, but your striker has a defender on him and the keeper is close."]],pro:1},
{cat:'cross',role:'RIGHT WINGER',min:"55'",sc:'0-0',q:"You have the ball wide, about 30 metres from goal.",
 p:[['gk','them',34,1.5,'GK'],['me',0,59,23,''],['them',0,40,13,'CB'],['them',0,31,12.5,'CB'],['them',0,22,14,'FB'],['them',0,54,17,'FB'],['us',0,33,19,'ST'],['them',0,40,28,'CM']],ball:[58,22],run:[33,19,32,7],
 o:[['Take it on to the byline',1,[59,23,64,3],"Not wrong, but by the time you get there their defenders are back and set."],
    ['Whip it in early, between their defenders and the keeper',2,[59,23,32,7],"Their back line is still running back towards their own goal, and your striker is already attacking the space. Coaches call it the corridor of uncertainty: defenders can't attack the ball and the keeper can't come for it."],
    ['Cut inside and shoot',0,[59,23,44,16],"Long range with a defender in front. Your striker's run is the better chance."]],pro:1},
{cat:'move',role:'RIGHT WINGER',min:"20'",sc:'0-0',q:"Your midfielder has the ball. Their full-back has followed you every time you've come short.",
 p:[['gk','them',34,2,'GK'],['me',0,63,38,''],['them',0,62,35,'FB'],['them',0,42,18,'CB'],['them',0,30,18,'CB'],['us',0,40,47,'CM'],['us',0,34,22,'ST']],ball:[40,45.5],
 o:[['Come short to his feet again',0,[63,38,62,44],"From my notes: you get it with your back to the game, pinned against the line, and can't move the play forward. Same as every time."],
    ['Spin in behind the full-back',2,[63,38,64,12],"He's tight on you and the center back is far away, so there's huge space behind him. From my notes: use it. After a few runs he drops off, and then you can receive and turn."],
    ['Drift inside between full-back and center back',1,[63,38,52,26],"Clever, but now nobody is wide, and the center back can step out to you."]],pro:1},
{cat:'shoot',role:'RIGHT WINGER (LEFT-FOOTED)',min:"65'",sc:'0-0',q:"You've cut inside onto your left foot.",
 p:[['gk','them',34,2,'GK'],['me',0,48,20,''],['them',0,44,15.5,'CB'],['them',0,32,12,'CB'],['them',0,38,9,'FB'],['us',0,30,9,'ST'],['them',0,56,24,'FB']],ball:[47,19],
 o:[['Shoot, far post',2,[48,20,31,-0.5],"The center back is 5 metres off you and backing away, so he's giving you the shot. Take it. Cut in and curl it far post. If he'd closed you down, then you look for a runner."],
    ['Slip it to your striker',1,[48,20,30,9],"Their full-back has him. Possible, but tight."],
    ['Keep dribbling at the center back',0,[48,20,40,13],"Now you're running into two defenders. The shooting window was right now."]],pro:0},
{g:'your goal',cat:'track',role:'RIGHT WINGER',min:"60'",sc:'1-1',q:"They have the ball in midfield, on your side.",
 p:[['gk','us',34,2,'GK'],['me',0,52,32,''],['them',0,60,38,'FB'],['them',0,40,40,'CM'],['them',0,62,22,'W'],['us',0,60,18,'FB'],['us',0,40,16,'CB'],['us',0,40,30,'CM']],ball:[41,38.5],run:[60,38,63,12],
 o:[['Press the player on the ball',1,[52,32,42,38],"Your midfielder is closer to him. If you go, their full-back is free."],
    ['Stay up for the counter attack',0,[52,32,52,40],"Look at your full-back: if their full-back keeps running, he's 2v1. If they cross and score, nobody remembers your counter."],
    ['Follow the full-back\'s run',2,[52,32,62,14],"Their full-back is overlapping, and your full-back already has their winger. From my notes on Bale: when the full-back goes, he follows him, even back into the defensive line."]],pro:2},
{cat:'react',role:'LEFT WINGER',min:"40'",sc:'1-1',q:"You've just lost the ball on the left. Your team is pushed up high.",
 p:[['me',0,15,28,''],['them',0,18,32,'FB'],['them',0,32,40,'CM'],['them',0,52,44,'W'],['us',0,34,26,'CM'],['us',0,30,50,'CB'],['us',0,40,50,'CB']],ball:[18.5,30.8],v:[-4,60],
 o:[['Press him straight away',2,[15,28,18,31],"He hasn't looked up yet, and your midfielder is close to help. The best moment to win it back is the second you lose it. Five hard seconds, then drop."],
    ['Get back into your position',1,[15,28,10,44],"Better than nothing, but your team is high and he has time to play the long ball."],
    ['Cut off the pass inside to their midfielder',1,[15,28,24,36],"Smart, but slower. He can still go down the line."]],pro:0}
],
ten:[
{cat:'pass',role:'NUMBER 10',min:"55'",sc:'0-0',q:"You get the ball between their lines, facing goal. Their center back comes out to you.",
 p:[['gk','them',34,2.5,'GK'],['me',0,33,29,''],['them',0,34,24,'CB'],['them',0,25,17,'CB'],['them',0,48,17,'FB'],['us',0,40,18,'ST'],['us',0,20,40,'CM'],['them',0,40,37,'CM']],ball:[33,27.8],run:[40,18,37,7],
 o:[['Shoot from 30 metres',0,[33,29,34,0],"The center back is closing you, so it's probably blocked."],
    ['Play it into the space he left',2,[33,29,36,9],"When a center back steps out, he leaves a hole, and your striker is already running into it. The best 10s see it before the ball arrives."],
    ['Lay it off to your midfielder',1,[33,29,21,39],"Safe, but you had the chance to put your striker through."]],pro:1},
{cat:'scan',role:'NUMBER 10',min:"30'",sc:'0-0',q:"The ball is coming to you between their lines. You checked your shoulder.",
 p:[['gk','them',34,2.5,'GK'],['me',0,34,31,''],['them',0,27,37,'CM'],['them',0,43,38,'CM'],['them',0,30,17,'CB'],['them',0,40,17,'CB'],['us',0,34,52,'CB'],['us',0,44,19,'ST']],pass:[34,52,34,33],v:[-4,58],
 o:[['Play it back first time',1,[34,31,34,50],"Never wrong. But look behind you: nobody's within 8 metres. That's wasted."],
    ['Control it facing your own goal and hold',0,[34,31,34,32],"Receiving square lets their midfielders recover and squeeze you."],
    ['Open up, receive on the half-turn and drive at them',2,[34,31,36,22],"Your scan showed space behind you. Receive side-on, with your back foot, and you're facing goal in one touch, running at a back line that has to react."]],pro:2},
{cat:'shoot',role:'NUMBER 10',min:"75'",sc:'0-0',q:"You have the ball about 22 metres out, central.",
 p:[['gk','them',34,2,'GK'],['me',0,34,22,''],['them',0,29,17,'CB'],['them',0,40,15,'CB'],['them',0,47,12,'FB'],['us',0,46,10,'W'],['them',0,30,28,'CM']],ball:[34,20.8],run:[46,10,43,5],
 o:[['Shoot low to the far post',2,[34,22,31,-0.5],"Neither center back is stepping to you, so there's a clear lane. From my notes on Dybala and Asensio: shoot from distance, hard and accurate to the far post."],
    ['Slip in your winger\'s run',1,[34,22,43,6],"Their full-back is tracking him. Possible, but the shot is the better chance."],
    ['Dribble at the center backs',0,[34,22,34,15],"You'd be running into two defenders. The shooting window is now."]],pro:0},
{cat:'move',role:'NUMBER 10',min:"35'",sc:'0-0',q:"Your center back has the ball. You're between their lines.",
 p:[['gk','them',34,2,'GK'],['me',0,34,22,''],['them',0,34,24,'CM'],['them',0,24,20,'CM'],['them',0,44,20,'CM'],['them',0,28,12,'CB'],['them',0,40,12,'CB'],['us',0,34,50,'CB'],['us',0,38,14,'ST']],ball:[34,48.6],v:[-4,56],
 o:[['Stay between their lines',0,[34,22,34,22.5],"Their midfield is sitting right on top of their defence. There's no space for you there."],
    ['Drop deeper to get it facing forward',2,[34,22,30,38],"When there's no space between the lines, the 10 drops to receive facing forward. If their midfielder follows you, the space you left opens up for your striker."],
    ['Run in behind their defence',1,[34,22,36,6],"Good against a high line. They're so deep there are only 12 metres behind them."]],pro:1},
{cat:'move',role:'NUMBER 10',min:"60'",sc:'0-0',q:"Your left winger is about to cross. You're on the edge of the box.",
 p:[['gk','them',33,1.5,'GK'],['me',0,33,19,''],['us',0,8,8,'W'],['us',0,30,8,'ST'],['them',0,29,6,'CB'],['them',0,35,7,'CB'],['them',0,36,18,'CM'],['them',0,47,8,'FB']],ball:[9,8.5],
 o:[['Hold at the edge for the second ball',1,[33,19,34,21],"Someone needs to be there, but their midfielder is already covering it."],
    ['Arrive late into the box, towards the far side',2,[33,19,42,8],"Their defenders are all on your striker. From my notes: when it's crossed from the other side, a great 10 arrives late and finishes first time into the far corner."],
    ['Attack the near post with your striker',0,[33,19,28,5],"Two of theirs are already there with your striker. You'd make it easier to defend."]],pro:1},
{cat:'move',role:'NUMBER 10',min:"45'",sc:'0-0',q:"Your striker drops short to get the ball.",
 p:[['gk','them',34,2,'GK'],['me',0,44,25,''],['us',0,34,27,'ST'],['them',0,34,24,'CB'],['them',0,24,15,'CB'],['them',0,50,15,'FB'],['us',0,34,46,'CM']],ball:[34,44.6],pass:[34,46,34,28.5],v:[-4,56],
 o:[['Run into the space the center back left',2,[44,25,37,10],"Look where their center back went: he followed your striker. From my notes: when the striker drops, there's a lot of space up top. That's where the chances come from."],
    ['Come short as well',0,[44,25,40,32],"Now two of you are in the same space, and nobody's threatening their goal."],
    ['Move wide to give him an option',1,[44,25,58,26],"A safe option, but you're missing the biggest gap on the pitch."]],pro:0},
{cat:'pass',role:'NUMBER 10',min:"80'",sc:'0-0',q:"You're on the edge of the box with a defender closing you.",
 p:[['gk','them',34,2,'GK'],['me',0,34,20,''],['them',0,37,23,'CM'],['us',0,29,15,'ST'],['them',0,28,12,'CB'],['them',0,38,12,'CB'],['them',0,46,14,'FB']],ball:[34,18.8],
 o:[['Shoot through the bodies',0,[34,20,34,0],"Three defenders between you and goal. It gets blocked."],
    ['Pass to your striker and sprint for the one-two',2,[34,20,36,9],"The center back is behind your striker, not in front, so he can play it first time. From my notes: pass, sprint, get it back, and you're in behind."],
    ['Turn back and recycle',1,[34,20,32,32],"Safe, but you were in the danger zone."]],pro:1},
{cat:'react',role:'NUMBER 10',min:"40'",sc:'0-0',q:"You've just lost the ball in the middle.",
 p:[['me',0,34,34,''],['them',0,35,38,'CM'],['them',0,20,46,'CM'],['them',0,52,46,'W'],['us',0,24,32,'CM'],['us',0,44,32,'CM'],['us',0,30,55,'CB'],['us',0,40,55,'CB']],ball:[35.5,36.8],v:[-4,62],
 o:[['Drop back and protect the middle',1,[34,34,34,48],"Solid, but he's facing his own goal and hasn't turned yet. Wasted chance."],
    ['Foul him straight away',0,[34,34,35,37],"A cheap free kick and maybe a yellow."],
    ['Press him straight away',2,[34,34,35,37],"From my notes on Foden: if he loses the ball, he presses straight away and wins it back. Their player is facing his own goal, and your midfielders are close to help."]],pro:2}
],
mid:[
{cat:'scan',role:'CENTRAL MIDFIELDER',min:"30'",sc:'0-0',q:"Your center back passes to you. A defender is on your back. You checked your shoulder.",
 p:[['me',0,34,48,''],['them',0,34,44.5,'CM'],['us',0,34,68,'CB'],['them',0,47,40,'CM'],['us',0,14,40,'FB'],['us',0,56,42,'W'],['them',0,24,28,'CB'],['us',0,36,24,'ST']],pass:[34,68,34,50],v:[10,72],
 o:[['Play it back to the center back',1,[34,48,34,66],"Safe and never really wrong. But your scan showed space on your left."],
    ['Hold it and wait for help',0,[34,48,34,49],"Holding the ball with a defender on your back invites the tackle."],
    ['Spin him on your first touch, to your left',2,[34,48,24,40],"Your scan showed nobody on your left. Take your first touch away from where the defender is coming from, and you're past him facing forward."]],pro:2},
{cat:'switchp',role:'CENTRAL MIDFIELDER',min:"25'",sc:'0-0',q:"You have the ball. Your left back is next to you.",
 p:[['me',0,28,44,''],['us',0,8,42,'FB'],['them',0,12,36,'W'],['them',0,22,36,'CM'],['them',0,30,34,'CM'],['them',0,20,22,'CB'],['them',0,36,22,'CB'],['us',0,62,28,'W'],['them',0,50,24,'FB']],ball:[29.5,43],v:[6,66],
 o:[['Switch it to your right winger',2,[28,44,61,29],"Look at their shape: everyone has shifted over to your left. Your right winger is 1v1, with their full-back 10 metres off him."],
    ['Play it back to your left back',1,[28,44,9,43],"Keeps the ball, but keeps it where they're strongest."],
    ['Force it forward through the middle',0,[28,44,30,26],"Their midfielders and center backs are stacked there."]],pro:0},
{cat:'pass',role:'CENTRAL MIDFIELDER',min:"35'",sc:'0-0',q:"You're receiving with a player tight on your back.",
 p:[['me',0,34,46,''],['them',0,34,49.5,'CM'],['us',0,46,48,'CM'],['them',0,46,36,'CM'],['them',0,24,40,'W'],['us',0,24,28,'W'],['us',0,34,66,'CB']],pass:[34,66,34,48],v:[10,72],
 o:[['Turn anyway',0,[34,46,30,38],"With a defender touching your back, that's how you lose it in the middle of the pitch."],
    ['Lay it off first time to your other midfielder',2,[34,46,45,47],"He's facing forward with nobody near him. If you can't turn, find the player who can. Then move and get it back."],
    ['Shield it and wait',1,[34,46,34,47],"You might keep it, but their team gets time to press everyone else."]],pro:1},
{cat:'shape',role:'CENTRAL MIDFIELDER',min:"15'",sc:'0-0',q:"Your center back is about to pass to you.",
 p:[['me',0,30,46,''],['us',0,26,66,'CB'],['them',0,42,40,'CM'],['them',0,20,36,'CM'],['us',0,54,32,'W'],['us',0,12,30,'W'],['them',0,34,22,'CB']],pass:[26,66,29.5,48],v:[10,72],
 o:[['Receive facing your center back',0,[30,46,30,47],"Now you need an extra touch just to turn around, and their midfielder closes you."],
    ['Come closer to him to make the pass easier',1,[30,46,28,54],"Safer pass, but you move away from the space."],
    ['Stand side-on and take it across your body',2,[30,46,40,34],"Nobody's within 10 metres of you. With an open body you see the whole pitch, and your first touch takes you forward. The best midfielders receive like this every time."]],pro:2},
{cat:'state',role:'CENTRAL MIDFIELDER',min:"88'",sc:'2-1',q:"You win the ball in midfield. 2-1 up, two minutes left.",
 p:[['me',0,34,44,''],['them',0,38,40,'CM'],['us',0,18,48,'FB'],['us',0,50,48,'CM'],['them',0,28,32,'CM'],['us',0,36,22,'ST'],['them',0,32,18,'CB'],['them',0,42,18,'CB']],ball:[35,42.6],v:[6,66],
 o:[['Try the pass over the top to your striker',0,[34,44,36,8],"Two center backs and the keeper are waiting. If it fails, they have the ball again."],
    ['Keep it with a simple pass',2,[34,44,49,47],"Winning late, the ball is your best defender. Your teammate is free. Short, safe passes, and make them chase."],
    ['Dribble forward',1,[34,44,34,34],"Can win a foul, but if you lose it, they're attacking."]],pro:1},
{g:'your goal',cat:'delay',role:'CENTRAL MIDFIELDER',min:"50'",sc:'1-1',q:"They break. Their midfielder runs at you with the ball.",
 p:[['gk','us',34,2,'GK'],['me',0,34,32,''],['them',0,35,40,'CM'],['them',0,54,38,'W'],['them',0,20,36,'ST'],['us',0,28,18,'CB'],['us',0,42,20,'CB'],['us',0,52,46,'CM']],ball:[35.5,38.6],run:[52,46,48,34],
 o:[['Slow him down and show him wide',2,[34,32,40,34],"Your center backs are set, and your teammate is sprinting back. Get side-on, don't dive, and push him wide. Every second you win, the 3v3 becomes 3v4."],
    ['Dive in for the tackle',0,[34,32,35,38],"Miss it and it's 3v2 against your center backs."],
    ['Take a tactical foul',1,[34,32,35,38],"Sometimes smart, but it costs a yellow. First try to slow him down."]],pro:0},
{cat:'pass',role:'CENTRAL MIDFIELDER',min:"60'",sc:'0-0',q:"You have the ball. Their midfield has pushed up to press.",
 p:[['me',0,34,44,''],['them',0,30,38,'CM'],['them',0,40,38,'CM'],['them',0,26,20,'CB'],['them',0,42,20,'CB'],['us',0,35,26,'ST'],['us',0,58,44,'W'],['gk','them',34,2,'GK']],ball:[34.5,42.5],v:[-4,60],
 o:[['Play it wide',1,[34,44,57,44],"Safe, but you let them reset."],
    ['Pass over the top',0,[34,44,36,8],"Their center backs are deep and the keeper is behind them. It just goes to them."],
    ['Play it into your striker\'s feet, between their midfielders',2,[34,44,35,28],"Look at the gap between their midfielders and their defence. One pass breaks their whole midfield line. Then sprint up to support him."]],pro:2},
{cat:'shoot',role:'CENTRAL MIDFIELDER',min:"70'",sc:'0-0',q:"Your winger cuts it back to you on the edge of the box.",
 p:[['gk','them',34,2,'GK'],['me',0,34,19,''],['us',0,60,5,'W'],['them',0,29,10,'CB'],['them',0,40,9,'CB'],['them',0,45,18,'CM'],['us',0,22,15,'W']],pass:[60,5,34,18],
 o:[['Shoot first time, low',2,[34,19,31,-0.5],"Their midfielder is 11 metres away and the lane to goal is open. The cut-back is made for a first-time shot. Low and hard is hardest to save through bodies."],
    ['Take a touch to set yourself',1,[34,19,33,17],"That's the extra second their midfielder needs to block."],
    ['Pass to your other winger',0,[34,19,22,15],"You're in the better spot. Take responsibility."]],pro:0}
],
def:[
{g:'your goal',cat:'line',role:'CENTER BACK',min:"20'",sc:'0-0',q:"Their midfielder has the ball. Their striker is on your shoulder.",
 p:[['gk','us',34,2,'GK'],['me',0,31,24,''],['them',0,33,46,'CM'],['them',0,34,25,'ST'],['us',0,20,24,'CB'],['us',0,46,25,'FB'],['us',0,40,36,'CM'],['us',0,24,38,'CM']],ball:[33,44.6],v:[-4,58],
 o:[['Step up to squeeze the space',0,[31,24,31,34],"Look at the ball: nobody's pressing him. He can play it over your head into all the space you just left."],
    ['Drop a few metres and protect the space behind',2,[31,24,31,17],"No pressure on the ball means a pass in behind is coming. Drop, and keep the striker in front of you. When your midfield presses him again, step back up."],
    ['Stay where you are',1,[31,24,31,24],"Not terrible, but a quick striker gets the first step on you."]],pro:1},
{g:'your goal',cat:'line',role:'CENTER BACK',min:"30'",sc:'0-0',q:"They pass into their striker's feet.",
 p:[['gk','us',34,2,'GK'],['me',0,34,22,''],['them',0,34,26,'ST'],['them',0,34,46,'CM'],['us',0,22,20,'CB'],['us',0,46,20,'FB'],['us',0,38,32,'CM'],['us',0,28,32,'CM']],pass:[34,46,34,27],v:[-4,56],
 o:[['Step in tight and stop him turning',2,[34,22,34,25],"His back is to goal, and your center back partner and midfielders are covering. That's your moment: get tight, touch him, don't let him turn."],
    ['Stay off and wait',1,[34,22,34,21],"Gives him time to turn and run at you."],
    ['Go round him for the interception',0,[34,22,34,30],"If you're late, he turns into the space and he's through."]],pro:0},
{g:'your goal',cat:'delay',role:'CENTER BACK',min:"55'",sc:'0-0',q:"Their winger runs at you in the channel.",
 p:[['gk','us',34,2,'GK'],['me',0,48,18,''],['them',0,51,28,'W'],['us',0,34,16,'CB'],['us',0,56,34,'FB'],['them',0,34,24,'ST']],ball:[51,26.6],run:[56,34,52,24],
 o:[['Dive in to win it',0,[48,18,51,26],"Against a quick player, one dive and he's past you, in your box."],
    ['Back off into your box',1,[48,18,46,10],"Buys time, but too far and he shoots."],
    ['Get side-on and show him down the line',2,[48,18,54,20],"Your full-back is sprinting back and your partner is covering their striker. Jockey, stay on your feet, and push him wide, away from goal."]],pro:2},
{g:'your goal',cat:'cover',role:'CENTER BACK',min:"85'",sc:'1-1',q:"The ball drops to you in your box after a corner.",
 p:[['gk','us',34,2,'GK'],['me',0,34,11,''],['them',0,30,14,'ST'],['them',0,39,14,'CB'],['us',0,26,8,'CB'],['them',0,44,20,'CM']],ball:[34.5,12.2],
 o:[['Pass it back to your keeper',1,[34,11,34,3],"Safe if he's ready, but their striker can still block it."],
    ['Clear it high and wide',2,[34,11,66,34],"Two of theirs are closing you in your own box. Safety first. High and wide gives your team time to reset."],
    ['Take a touch and play out',0,[34,11,40,16],"Lose it here and it's a goal."]],pro:1},
{g:'your goal',cat:'build',role:'CENTER BACK',min:"10'",sc:'0-0',q:"Your keeper passes to you. Their striker comes to press you.",
 p:[['gk','us',34,2,'GK'],['me',0,24,12,''],['them',0,29,16,'ST'],['us',0,34,26,'CM'],['them',0,35,30,'10'],['us',0,6,24,'FB'],['them',0,14,34,'W'],['us',0,44,12,'CB']],pass:[34,2,25,11],v:[-4,52],
 o:[['Play it to your free full-back',2,[24,12,7,23],"Their striker came to you, so the space is wide. Their winger is 10 metres from your full-back. Find the free man and you're through their first line."],
    ['Kick it long',1,[24,12,40,70],"Safe, but you're giving the ball away 50/50 when a free pass was on."],
    ['Force it into your midfielder',0,[24,12,33,25],"Their 10 is right behind him. A pass into a marked player in your own half is how goals are conceded."]],pro:0},
{g:'your goal',cat:'cover',role:'CENTER BACK',min:"40'",sc:'0-0',q:"Your partner center back steps out to press their striker.",
 p:[['gk','us',34,2,'GK'],['me',0,42,18,''],['us',0,27,26,'CB'],['them',0,26,29,'ST'],['them',0,40,24,'10'],['us',0,58,20,'FB'],['them',0,26,46,'CM']],pass:[26,46,26,30],v:[-4,54],
 o:[['Push up with him',0,[42,18,42,26],"Now there's nobody behind either of you."],
    ['Tuck in and cover the space behind him',2,[42,18,32,16],"When one center back steps, the other covers. If their striker flicks it on or turns, you're there."],
    ['Stay with their 10',1,[42,18,40,22],"He's a threat, but the space behind your partner is the bigger danger."]],pro:1},
{g:'your goal',cat:'state',role:'CENTER BACK',min:"90+2'",sc:'1-0',q:"The ball comes to you. 1-0 up, stoppage time.",
 p:[['gk','us',34,2,'GK'],['me',0,30,24,''],['them',0,34,28,'ST'],['us',0,14,30,'FB'],['us',0,40,36,'CM'],['them',0,42,40,'CM']],pass:[14,30,29,25],v:[-4,56],
 o:[['Play it out through the middle',0,[30,24,40,35],"Their striker is closing you and their midfielder is near yours. One mistake and it's 1-1."],
    ['Pass it back to your keeper',1,[30,24,34,4],"Safe, but their striker follows it and it stays near your goal."],
    ['Kick it long towards their corner',2,[30,24,66,100],"With seconds left, the safest place for the ball is far from your goal. Towards their corner, they need the whole pitch to come back."]],pro:2},
{g:'your goal',cat:'aerial',role:'CENTER BACK',min:"65'",sc:'0-0',q:"A cross is coming in from their left. You're marking their striker.",
 p:[['gk','us',34,2,'GK'],['me',0,33,12,''],['them',0,34.5,13.5,'ST'],['them',0,6,14,'W'],['us',0,40,9,'FB'],['them',0,42,16,'CM']],pass:[6,14,33,10],
 o:[['Let it drop and clear it',0,[33,12,33,13],"The striker attacks it before you."],
    ['Attack the ball first and head it away',2,[33,12,32,10],"You're goal-side of him and the ball is coming into your zone. First to the ball wins: head it high and wide, away from the middle."],
    ['Stay tight on the striker',1,[33,12,34,13],"Marking is right, but if you don't go for the ball, he gets a free header."]],pro:1}
]};
